pipeline {
    agent 'any'

    stages {
        stage("shutdown"){
            steps {
                sh 'docker-compose down'
            }
        }

        stage("build"){
            steps {
                docker.build('im-api-server', 'WebServer')
            }
        }

        stage("deploy"){
            steps {
                sh './deploy.sh'
            }
        }
    }
}